### ISSUE TITLE
Update podspec

### ISSUE THREAD

**Issue by JARMourato** [kgn/KGNAutoLayout#3]
Whenever you've got the time, please push the latest version of podspec to the cocoapods trunk. Cheers

**Comment by kgn** [comment]
I was trying to last night actually, but ran into an error I hadn't come across in testing. Gonna try to sort it out tonight or tomorrow.

```
 -> KGNAutoLayout (1.5.1)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR | [iOS] xcodebuild:  KGNAutoLayout/Source/KGNAutoLayout.swift:15:11: error: 'UILayoutGuide' is only available on iOS 9.0 or newer
    - NOTE  | [iOS] xcodebuild:  KGNAutoLayout/Source/KGNAutoLayout.swift:15:11: note: add @available attribute to enclosing extension
```

**Comment by JARMourato** [comment]
Hey @kgn, thanks for the response. You can actually fix that error if you add _@available(iOS 9.0, *)_ above the line where _@available(iOSApplicationExtension 9.0, *)_ is. let me know if it fixed your error

**Comment by kgn** [comment]
Thanks for the tip! Xcode auto filled that `@available` statement and I totally missed it was just for `iOSApplicationExtension`.

Lint is passing now, but when I try to push to trunk I'm getting this warning:

```
[!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`
```

Any ideas on this? I'm not too familiar with CocoaPods, this kind of stuff is what drives me to Carthage ;)

**Comment by JARMourato** [comment]
Have you run pod repo update --verbose ? 

What command have you used to push to the trunk ?

**Comment by kgn** [comment]
that worked! thanks! https://cocoapods.org/pods/KGNAutoLayout
