### ISSUE TITLE
error: module compiled with Swift 3.0.2 cannot be imported in Swift 3.1

### ISSUE THREAD

**Issue by TofPlay** [kgn/KGNAutoLayout#6]
Generate this error with Carthage:
```
error: module compiled with Swift 3.0.2 cannot be imported in Swift 3.1: /Carthage/Build/iOS/KGNAutoLayout.framework/Modules/KGNAutoLayout.swiftmodule/arm64.swiftmodule
```

**Comment by kgn** [comment]
I think the issue is with the pre-built binary. I deployed a new release built with Xcode 8.3 should hopefully is good now: https://github.com/kgn/KGNAutoLayout/releases/tag/v1.5.5
